language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

script: for i in `find . -name "*.php"`; do php -l $i; done;

branches:
  only:
    - "master"

notifications:
  email: info@ubilling.net.ua
